services:
  blog:
    image: nginx
    container_name: blog
    restart: always
    ports:
      - 80:80
    #  - 443:443
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/build:/usr/share/nginx/html:ro

